name: sensor_tracker5
channels:
  - conda-forge
  - anaconda
  - hargup
  - pypi
  - hargup/label/pypi
dependencies:
- python=3.7
- django=2.2
- djangorestframework=3.9.4
- psycopg2=2.7.6.1
- Pillow=6.0.0
- django-debug-toolbar
- django-filter
- django-suit
- pyyaml
- pip:
  - drf-yasg
  - packaging
  - git+https://github.com/mrts/django-admin-list-filter-dropdown.git
  - git+ssh://git@gitlab.oceantrack.org/ceotr/app_common.git