name: sensor_tracker
channels:
  - conda-forge
  - anaconda
  - hargup
  - pypi
  - hargup/label/pypi
dependencies:
- python=3.6
- django=2.2
- pip
- djangorestframework=3.9.4
- psycopg2=2.7.6.1
- Pillow=6.0.0
- django-debug-toolbar
- django-filter
- pyyaml
- pip:
  - uwsgi==2.0.18
  - drf-yasg
  - packaging
  - django-suit
  - git+https://github.com/mrts/django-admin-list-filter-dropdown.git
  - git+ssh://git@gitlab.oceantrack.org/ceotr/app_common.git