# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-09 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='manufacturer_name',
            field=models.CharField(help_text='The formal name for the platform given by the manufacturer', max_length=300, null=True),
        ),
    ]
