# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-09 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170109_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrumentonplatform',
            old_name='end_date',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='instrumentonplatform',
            old_name='start_date',
            new_name='start_time',
        ),
    ]
