# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-24 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        ('platforms', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='The name used to identify this instrument in the raw data. IE: SATCTD7229, sea_water', max_length=300)),
                ('short_name', models.CharField(help_text='The short, general name for the instrument. IE: ctd, fluorometer', max_length=50)),
                ('long_name', models.CharField(blank=True, help_text='The full name for the instrument', max_length=300, null=True)),
                ('serial', models.CharField(blank=True, max_length=300, null=True)),
                ('comment', models.TextField(blank=True, help_text="This is a good place to document anything unusual about this instrument's configuration", null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Manufacturer')),
                ('master_instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.Instrument')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text='This is a good place to log any problems or changes with an instrument')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument')),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentOnPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='The date the instrument was put on the platform')),
                ('end_time', models.DateTimeField(blank=True, help_text='The date the instrument was removed from the platform', null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('instrument', models.ForeignKey(help_text='The instrument that was put on a platform', on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument')),
                ('platform', models.ForeignKey(help_text='The platform that the instrument was put on', on_delete=django.db.models.deletion.CASCADE, to='platforms.Platform')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='The name used to identify this sensor in the raw data. ie: sci_water_temp', max_length=300)),
                ('long_name', models.CharField(blank=True, help_text='The general name for the sensor. IE: temperature', max_length=50, null=True)),
                ('standard_name', models.CharField(blank=True, help_text="The official, standard name for the instrument. IE: sea_water_temperature. See CF naming: <a href='http://cfconventions.org/Data/cf-standard-names/39/build/cf-standard-name-table.html'>CF Naming Reference</a>", max_length=300, null=True)),
                ('type', models.CharField(blank=True, choices=[('f4', '32-bit floating point'), ('f8', '64-bit floating point'), ('i4', '32-bit signed integer'), ('i2', '16-bit signed integer'), ('i8', '64-bit signed integer'), ('i1', '8-bit signed integer'), ('u1', '8-bit unsigned integer'), ('u2', '16-bit unsigned integer'), ('u4', '32-bit unsigned integer'), ('u8', '64-bit unsigned integer'), ('S1', 'single-character string')], default='f8', help_text='Storage datatype to use for this sensor.<b>The default is correct for most sensors</b>', max_length=2)),
                ('units', models.CharField(blank=True, help_text='The units for the sensor. <b>Please verify after adding a new sensor</b>', max_length=30, null=True)),
                ('valid_min', models.FloatField(blank=True, help_text='The minimum possible value that the sensor could produce', null=True)),
                ('valid_max', models.FloatField(blank=True, help_text='The maximum possible value that the sensor could produce', null=True)),
                ('include_in_output', models.BooleanField(default=False, help_text='Whether or not data from this sensor should be included in any processed output.')),
                ('comment', models.TextField(blank=True, help_text='This is a good place to document anything unusual about this particular sensor. IE: wavelengths for spectral sensors', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument')),
            ],
        ),
    ]
