# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='standard_name',
            field=models.CharField(blank=True, help_text="The official, standard name for the instrument. IE: sea_water_temperature. See CF naming: <a href='http://cfconventions.org/standard-names.html'>CF Naming Reference</a>", max_length=300, null=True),
        ),
    ]
