# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='accuracy',
            field=models.FloatField(blank=True, help_text='The accuracy of a sensor is the closeness to true values. Average distance from a known, true value', null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='precision',
            field=models.FloatField(blank=True, help_text='The precision of a sensor is the consistency for repeated measurements. Average deviation about the mean', null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='resolution',
            field=models.FloatField(blank=True, help_text='The resolution of a sensor is the smallest change it can detect in the quantity that it is measuring.', null=True),
        ),
    ]
