# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-11 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0002_auto_20190416_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentcomment',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumentonplatform',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='instrumentonplatform',
            name='modified_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
