# Generated by Django 2.2 on 2019-06-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0003_auto_20190611_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='general.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='instrumentonplatform',
            name='instrument',
            field=models.ForeignKey(help_text='The instrument that was put on a platform', on_delete=False, to='instruments.Instrument'),
        ),
        migrations.AlterField(
            model_name='instrumentonplatform',
            name='platform',
            field=models.ForeignKey(help_text='The platform that the instrument was put on', on_delete=False, to='platforms.Platform'),
        ),
    ]
