# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-18 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0005_instrumentcommentbox_instrumentcommentinbox'),
    ]

    operations = [
        migrations.RunSQL(
            "insert into instruments_instrumentcommentbox(instrument_id) select DISTINCT  instrument_id from instruments_instrumentcomment"
        ),
        migrations.RunSQL(
            "insert into instruments_instrumentcommentinbox(comment, created_date, modified_date, instrument_comment_box_id) select a.comment, a.created_date, a.modified_date, b.id from instruments_instrumentcomment AS a LEFT JOIN instruments_instrumentcommentbox as b on a.instrument_id = b.instrument_id"
        ),
    ]
