# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-18 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0006_migrate_data_from_ol_instrument_comment_to_new_instrument_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrumentcomment',
            name='instrument',
        ),
        migrations.DeleteModel(
            name='InstrumentComment',
        ),
    ]
