# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-18 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0007_auto_20190618_1329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstrumentCommentInBox',
            new_name='InstrumentComment',
        ),
    ]
