# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-19 17:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0007_auto_20190618_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorOnInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='The date the instrument was put on the platform')),
                ('end_time', models.DateTimeField(blank=True, help_text='The date the instrument was removed from the platform', null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('instrument', models.ForeignKey(help_text='The instrument that was put on a platform', on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument')),
                ('sensor', models.ForeignKey(help_text='The platform that the instrument was put on', on_delete=django.db.models.deletion.CASCADE, to='instruments.Sensor')),
            ],
        ),
        migrations.AlterField(
            model_name='instrumentcomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
