# Generated by Django 2.2 on 2019-06-20 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0008_auto_20190618_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentcomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
