# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-19 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0008_auto_20190618_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentcomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
