# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-19 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0008_auto_20190619_1703'),
    ]

    operations = [
        migrations.RunSQL(
            "insert into instruments_sensoroninstrument(instrument_id, sensor_id,start_time) select s.instrument_id, s.id, NOW() from instruments_sensor as s"
        ),
    ]
