# Generated by Django 2.2 on 2019-07-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0010_auto_20190620_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='instrument',
        ),
        migrations.CreateModel(
            name='SensorOnInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(help_text='The date the instrument was put on the platform')),
                ('end_time', models.DateTimeField(blank=True, help_text='The date the instrument was removed from the platform', null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('instrument', models.ForeignKey(help_text='The instrument that was put on a platform', on_delete=False, to='instruments.Instrument')),
                ('sensor', models.ForeignKey(help_text='The platform that the instrument was put on', on_delete=False, to='instruments.Sensor')),
            ],
        ),
    ]
