# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-19 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0012_sensor_sensor_in_instrument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='instrument',
        ),
    ]
