# Generated by Django 2.2 on 2019-06-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0013_remove_sensor_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensoroninstrument',
            name='instrument',
            field=models.ForeignKey(help_text='The instrument that was put on a platform', on_delete=False, to='instruments.Instrument'),
        ),
        migrations.AlterField(
            model_name='sensoroninstrument',
            name='sensor',
            field=models.ForeignKey(help_text='The platform that the instrument was put on', on_delete=False, to='instruments.Sensor'),
        ),
    ]
