# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-19 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('instruments', '0015_sensor_instrument'),
    ]

    operations = [
        migrations.RunSQL(
            """
update
      instruments_sensor as A
set
      instrument_id = instruments_sensoroninstrument.instrument_id
FROM
       instruments_sensoroninstrument
where
      A.id = instruments_sensoroninstrument.sensor_id
and
      instruments_sensoroninstrument.end_time  is NULL

"""
        ),
    ]
