# Generated by Django 2.2.6 on 2019-11-08 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0016_sensor_instrument_data_migrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='instrument',
            field=models.ForeignKey(blank=True, help_text='The Instrument which this sensor currently attach on. Modified this field will auto change sensor on instrument table.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='instruments.Instrument'),
        ),
    ]
