# Generated by Django 2.2.6 on 2019-11-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0019_auto_20191115_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentonplatform',
            options={'verbose_name': 'Instrument on Platform History', 'verbose_name_plural': 'Instrument on Platform History'},
        ),
    ]
