# Generated by Django 2.2.6 on 2019-11-20 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0020_auto_20191115_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general.Manufacturer'),
        ),
        migrations.AlterField(
            model_name='instrumentonplatform',
            name='instrument',
            field=models.ForeignKey(help_text='The instrument that was put on a platform', on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument'),
        ),
        migrations.AlterField(
            model_name='instrumentonplatform',
            name='platform',
            field=models.ForeignKey(help_text='The platform that the instrument was put on', on_delete=django.db.models.deletion.CASCADE, to='platforms.Platform'),
        ),
        migrations.AlterField(
            model_name='sensoroninstrument',
            name='instrument',
            field=models.ForeignKey(help_text='The instrument that was put on a platform', on_delete=django.db.models.deletion.CASCADE, to='instruments.Instrument'),
        ),
        migrations.AlterField(
            model_name='sensoroninstrument',
            name='sensor',
            field=models.ForeignKey(help_text='The platform that the instrument was put on', on_delete=django.db.models.deletion.CASCADE, to='instruments.Sensor'),
        ),
    ]
