# Generated by Django 2.2.6 on 2019-11-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0021_auto_20191120_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentcommentbox',
            options={'verbose_name': 'Instrument Comment Box', 'verbose_name_plural': 'Instrument Comment Boxes'},
        ),
    ]
