# Generated by Django 2.2.6 on 2019-11-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0022_auto_20191121_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentcomment',
            name='event_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
