# Generated by Django 2.2.6 on 2019-12-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0023_instrumentcomment_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='serial',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
