# Generated by Django 2.2.5 on 2020-04-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0024_sensor_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether or not the sensor is decommissioned.'),
        ),
        migrations.AddField(
            model_name='sensoroninstrument',
            name='active',
            field=models.BooleanField(default=True, help_text='Whether or not the instrument is decommissioned.'),
        ),
    ]
