# Generated by Django 2.2.8 on 2020-04-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0024_sensor_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='model',
            field=models.TextField(blank=True, null=True),
        ),
    ]
