# Generated by Django 2.2.8 on 2020-02-26 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0024_sensor_serial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensor',
            unique_together={('identifier', 'instrument')},
        ),
    ]
