# Generated by Django 2.2.8 on 2020-04-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instruments', '0025_instrument_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='long_name',
            field=models.CharField(blank=True, help_text="*REQUIRED if 'Include in output' is checked. The general name for the sensor. IE: temperature", max_length=300, null=True),
        ),
    ]
