# Generated by Django 2.2.6 on 2019-11-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20191125_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='url',
            field=models.CharField(blank=True, help_text="The institution's URL", max_length=1000, null=True),
        ),
    ]
