# Generated by Django 2.2.8 on 2020-02-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20191125_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(help_text='Name of the institution', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(help_text='<b>Example:</b> Collaborative Operations with Mote Marine Laboratory', max_length=1000, unique=True),
        ),
    ]
