# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-14 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_auto_20190611_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='uploaded_media')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, null=True)),
                ('platform_deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platforms.PlatformDeployment')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
