# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_remove_platformdeployment_deployment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformdeployment',
            name='depth',
            field=models.FloatField(blank=True, help_text='The depth of the deployment', null=True),
        ),
        migrations.AddField(
            model_name='platformdeployment',
            name='latitude',
            field=models.FloatField(blank=True, help_text='The latitude of the deployment', null=True),
        ),
        migrations.AddField(
            model_name='platformdeployment',
            name='longitude',
            field=models.FloatField(blank=True, help_text='The longitude of the deployment', null=True),
        ),
    ]
