# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-12 19:32
from __future__ import unicode_literals

from django.db import  models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('platforms', '0003_auto_20190614_1948'),
    ]
    migrations.AddField(
        model_name='platform',
        name='active',
        field=models.BooleanField(default=True, help_text='check if the platform is currently active'),
    ),
    operations = [
        migrations.RunSQL(
            "update platforms_platform set active = false where platform_type_id = (select id from platforms_platformtype where model = 'VR3-UWM')"
        ),
        migrations.RunSQL(
            "update platforms_platform set active = false where platform_type_id = (select id from platforms_platformtype where model = 'VR4-UWM')"
        ),
    ]
