# Generated by Django 2.2 on 2019-06-12 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_auto_20190611_1951'),
        ('platforms', '0002_auto_20190527_1823'),
    ]

    operations = [
    ]
