# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-09-26 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_auto_20190611_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformdeployment',
            name='acknowledgement',
            field=models.TextField(blank=True, help_text='<b>Example:</b> This deployment is supported by funding from NOAA', null=True),
        ),
    ]
