# Generated by Django 2.2 on 2019-06-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_auto_20190611_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformdeployment',
            name='platform',
            field=models.ForeignKey(on_delete=False, to='platforms.Platform'),
        ),
    ]
