# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-14 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0003_auto_20190618_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='active',
            field=models.BooleanField(default=True, help_text='check if the platform is currently active'),
        ),
    ]
