# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-06-12 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [

        ('platforms', '0004_platform_active'),
    ]

    operations = [
        migrations.RunSQL(
            "update platforms_platform set active = false where platform_type_id = (select id from platforms_platformtype where model = 'VR3-UWM')"
        ),
        migrations.RunSQL(
            "update platforms_platform set active = false where platform_type_id = (select id from platforms_platformtype where model = 'VR4-UWM')"
        ),
    ]
