# Generated by Django 2.2.4 on 2019-09-18 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0006_remove_platformdeployment_platform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformdeployment',
            name='acknowledgement',
            field=models.TextField(blank=True, help_text='<b>Example:</b> This deployment is supported by funding from NOAA', null=True),
        ),
    ]
