# Generated by Django 2.2.6 on 2019-11-06 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0008_auto_20190930_1826'),
        ('platforms', '0003_auto_20190926_1437'),
    ]

    operations = [
    ]
