# Generated by Django 2.2.6 on 2019-11-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0012_platformcomment_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformdeploymentcomment',
            name='event_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
