# Generated by Django 2.2.8 on 2020-02-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0013_platformdeploymentcomment_event_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='platformdeployment',
            old_name='latitude',
            new_name='deployment_latitude',
        ),
        migrations.RenameField(
            model_name='platformdeployment',
            old_name='longitude',
            new_name='deployment_longitude',
        ),
        migrations.AddField(
            model_name='platformdeployment',
            name='deployment_cruise',
            field=models.TextField(blank=True, help_text='The cruise of the deployment', null=True),
        ),
        migrations.AddField(
            model_name='platformdeployment',
            name='recovery_cruise',
            field=models.TextField(blank=True, help_text='The cruise of the recovery', null=True),
        ),
        migrations.AddField(
            model_name='platformdeployment',
            name='recovery_latitude',
            field=models.FloatField(blank=True, help_text='The latitude of the recovery', null=True),
        ),
        migrations.AddField(
            model_name='platformdeployment',
            name='recovery_longitude',
            field=models.FloatField(blank=True, help_text='The longitude of the recovery', null=True),
        ),
    ]
