# Generated by Django 2.2.8 on 2020-02-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0014_auto_20200221_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformdeployment',
            name='deployment_personnel',
            field=models.CharField(blank=True, help_text='The personnel of the deployment', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='platformdeployment',
            name='recovery_personnel',
            field=models.CharField(blank=True, help_text='The personnel of the recovery', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='platformdeployment',
            name='deployment_cruise',
            field=models.CharField(blank=True, help_text='The cruise of the deployment', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='platformdeployment',
            name='recovery_cruise',
            field=models.CharField(blank=True, help_text='The cruise of the recovery', max_length=100, null=True),
        ),
    ]
