# Generated by Django 2.2.8 on 2020-04-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0015_auto_20200224_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformdeployment',
            name='agencies',
            field=models.TextField(blank=True, help_text='A comma separated list of agencies involved with this data set', null=True),
        ),
        migrations.AddField(
            model_name='platformdeployment',
            name='agencies_role',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformdeployment',
            name='contributors_email',
            field=models.TextField(blank=True, help_text='A comma separated list of the emails for those specified in the contributor_name attribute', null=True),
        ),
        migrations.AddField(
            model_name='platformdeployment',
            name='positioning_system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformdeployment',
            name='program',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformdeployment',
            name='site',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='platformdeployment',
            name='transmission_system',
            field=models.TextField(blank=True, null=True),
        ),
    ]
