# Generated by Django 2.2.8 on 2020-04-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0016_auto_20200415_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformdeployment',
            name='creator_sector',
            field=models.TextField(blank=True, help_text='Describes the platform (network) operator’s societal sector', null=True),
        ),
        migrations.AddField(
            model_name='platformdeployment',
            name='publisher_country',
            field=models.TextField(blank=True, help_text='Country of the person or organization that distributes the data', null=True),
        ),
        migrations.AlterField(
            model_name='platformdeployment',
            name='agencies_role',
            field=models.TextField(blank=True, help_text='A comma separated list of the roles for those specified in the agencies attribute, example: Funding agency, operating agency, scientific agency, reference data center', null=True),
        ),
        migrations.AlterField(
            model_name='platformdeployment',
            name='positioning_system',
            field=models.TextField(blank=True, help_text='Describes the positioning system used by the glider, example: GPS', null=True),
        ),
        migrations.AlterField(
            model_name='platformdeployment',
            name='program',
            field=models.TextField(blank=True, help_text='Name of the sustained/long term glider program supporting the glider mission. JCOMMOPS uses program to manage glider mission metadata. Example: NANOOS glider program / MOOSE / Balearic Island Observatory / IMOS glider program are programs in the JCOMMOPS system', null=True),
        ),
        migrations.AlterField(
            model_name='platformdeployment',
            name='site',
            field=models.TextField(blank=True, help_text='Name of the regularly sample line or area', null=True),
        ),
        migrations.AlterField(
            model_name='platformdeployment',
            name='transmission_system',
            field=models.TextField(blank=True, help_text='A comma separated list of the telecom technology used by the glider, example: Iridium,Freewave,Cellular', null=True),
        ),
    ]
